# Algebra Review

## Overview
Algebra, arthmetic, and probability are underlying frameworks for statistics.  The
following elements of algebra are particularly important:

* Understanding symbols as variables, and what they can stand for
* Factoring out common terms: $axw + bx = x(aw + b)$
* Factoring out negation of a series of added terms: $-a - b = -
  (a + b)$
* Simplification of fractions
* Addition, subtraction, multiplication, and division of fractions
* Exponentiation with both fractional and whole number exponents
* Re-writing exponentials of sums: $b^{u + v} = b^{u}\times b^{v}$
* Logarithms
    + log to the base $b$ of $x$ = $\log_{b}x$ is the number $y$ such
   that $b^{y} = x$
    + $\log_{b}b = 1$
    + $\log_{b}b^{x} = x \log_{b}b = x$
    + $\log_{b}a^{x} = x \log_{b}a$
    + $\log_{b}a^{-x} = -x \log_{b}a$
    + $\log_{b}(xy) = \log_{b}x + \log_{b}y$
    + $\log_{b}\frac{x}{y} = \log_{b}x - \log_{b}y$
    + When $b = e = 2.71828\ldots$, the base of the natural log,
   $\log_{e}(x)$ is often written as $\ln{x}$ or just $\log(x)$
    + $\log e = \ln e = 1$
* Anti-logarithms: anti-log to the base $b$ of $x$ is $b^{x}$
    + The natural anti-logarithm is $e^{x}$, often often written as
   $\exp(x)$
    + Anti-log is the inverse function of log; it 'undoes' a log
* Understanding functions in general, including $\min(x, a)$ and
  $\max(x, a)$
* Understanding indicator variables such as $[x=3]$ which can be
  thought of as true if $x=3$, false otherwise, or 1 if $x=3$, 0
  otherwise
    + $[x=3]\times y$ is $y$ if $x=3$, 0 otherwise
    + $[x=3]\times[y=2] = [x=3 \,\textrm{and}\, y=2]$
    + $[x=3] + 3\times [y=2] = 4$ if $x=3$ and $y=2$, $3$ if $y=2$
   and $x\neq 3$
    + $x\times \max(x, 0) = x^{2}[x>0]$
    + $\max(x, 0)$ or $w \times [x>0]$ are algebraic ways of saying
   to ignore something if a condition is not met
* Quadratic equations
* Graphing equations
Once you get to multiple regression, some elements of vectors/linear
algebra are helpful, for example the vector or dot product, also
called the inner product:

* Let $x$ stand for a vector of quantities $x_{1}, x_{2}, \ldots,
  x_{p}$ (e.g., the values of $p$ variables for an animal such as age,
  blood pressure, etc.)
* Let $\beta$ stand for another vector of quantities $\beta_{1},
  \beta_{2}, \ldots, \beta_{p}$ (e.g., weights / regression
  coefficients / slopes)
* Then $x\beta$ is shorthand for $\beta_{1}x_{1}+\beta_{2}x_{2} +
  \ldots + \beta_{p}x_{p}$
* $x\beta$ might represent a predicted value in multiple
  regression, and is known then as the <em>linear predictor</em>


## Some Resources

* [tutorial.math.lamar.edu/pdf/Algebra_Cheat_Sheet.pdf](http://tutorial.math.lamar.edu/pdf/Algebra_Cheat_Sheet.pdf)
* [www.khanacademy.org/math/algebra](https://www.khanacademy.org/math/algebra)
* [www.purplemath.com/modules/index.htm](http://www.purplemath.com/modules/index.htm)

## Algebra Prequisites

Students should have a good command of college algebra. Specifically, you
should have mastered variables, functions, grouped expressions,
algebraic fractions, polynomials, exponents, logarithms, and uses of
the mathematical constant $e$. If you need to review algebra, there
are many good study books and web sites. One good book is [Forgotten Algebra](http://www.amazon.com/Forgotten-Algebra-Barbara-Lee-Bleau/dp/0764120085/ref=pd_bbs_sr_1?ie=UTF8&s=books&qid=1201146512&sr=8-1), Second Edition by Barbara Bleau (Barrons Educational Series, Hauppauge, New York, 1994). You may skip the following Units in this book:

| *Topic* | *Unit<br>Numbers* |
|---------|-------------------|
|Division of polynomials|17|
|Factoring polynomials  |18|
|Solving second degree equations-quadratic formula|22|
|Solving third-degree and higher equations|23|
|Solving systems of equations|26-27|
|Solving inequalities-second-degree|29|
|Right triangles|31|

The topics to study, and corresponding unit numbers in Bleau's book (second edition, may need to be updated for the third edition),
are as follows.

| *Topic* | *Unit<br>Numbers* |
|---------|-------------------|
|Signed Numbers|1|
|Grouping Symbols and Simplifying Expressions|2|
|Solving First-Degree Equations|3|
|Removing Multiple Grouping Symbols; Solving 1st-Degree Eq.|4|
|Fraction Equations|5|
|Literal Equations|6|
|Applied Problems|7|
|Positive Integral Exponents|8|
|Negative Exponents|9|
|Division of Powers|10|
|Addition and Subtraction of Fractions|11|
|Multiplication and Division of Fractions|12|
|Fractional Exponents|13|
|Simplifying Expressions with Fractional Exponents|14|
|Additional Practice with Exponents|15|
|Multiplication of Monomials and Polynomials|16|
|Factoring Special Binomials|19-20|
|Factoring to Solve 2nd Degree Equations|21|
|Graphing Linear Equations in Two Variables|24|
|Graphing Quadratic Equations in Two Variables|25|
|Solving First-Degree Inequalities|28|
|Logarithms|30|

Note that in statistics one most often uses logarithms to the base
$e$ =2.71828..., and $\log x$ with no base indicated often means log to
the base $e$.

A more comprehensive but much more expensive book we also recommend is
_Intermediate Algebra_ by Alan Tussy and R. David Gustafson, Pacific
Grove CA, Brooks/Cole, 1999.
